<a href="https://colab.research.google.com/github/MelissaMF/DisenoInvestigacionS2-2026/blob/main/20261019_AvanceEvaluacionCuantitativa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
library(tidyverse)
library(readxl)
library(broom)

#Carga datos
datos <- read_excel("ptsd.xlsx", sheet=2)

Limpieza de Datos

In [3]:
#Datos nulos
colSums(is.na(datos))

                                            inum
                                               0
                                         a1_Sexo
                                               0
                                         a2_Edad
                                               0
                       a8_Años_Estudio_Categoria
                                               0
                             PTSD_Diagnostico_UA
                                               0
                            Violencias_infancias
                                               0
                       f32YE_Depresion_Simple_UA
                                               0
                 EEV_EC_1_Fallecimiento_familiar
                                               0
                   EEV_EC_2_Atrapado_y_rescatado
                                               0
EEV_EC_3_Lesiones_fisicas_Graves_Hospitalizacion
                                               0
          EEV_EC_4_Daño_grave_o_Perdida_Vivienda
                                               0
                                    EEV_EC_Final
                                               0
                         EEV_TE_1_Muerte_mascota
                                               0
                        EEV_TE_2_Muerte_familiar
                                               0
                        EEV_TE_3_Herido_familiar
                                               0
                   EEV_TE_4_Atrapado_y_rescatado
                                               0
EEV_TE_5_Lesiones_fisicas_Graves_Hospitalizacion
                                               0
                    EEV_TE_6_Sentir_Riesgo_vital
                                               0
                    EEV_TE_7_Tsunami_llego_cerca
                                               0
          EEV_TE_8_Daño_grave_o_Perdida_Vivienda
                                               0
                          EEV_TE_9_Victima_robos
                                               0
                    EEV_TE_10_Quedar_sin_trabajo
                                               0
            EEV_TE_11_Presencio_personas_heridas
                                               0
         EEV_TE_12_Presencio_personas_fallecidas
                                               0
         EEV_TE_13_Participo_en_rescate_personas
                                               0
      EEV_TE_14_Vio_construcciones_destruyendose
                                               0
                               EEV_TE_Suma_TOTAL
                                               0

In [4]:
#Tipos de datos
glimpse(datos)

Rows: 913
Columns: 27
$ inum                                             <dbl> 2, 4, 11, 21, 32, 35,…
$ a1_Sexo                                          <chr> "Femenino", "Femenino…
$ a2_Edad                                          <dbl> 60, 64, 45, 67, 73, 8…
$ a8_Años_Estudio_Categoria                        <chr> "Basica", "Media", "M…
$ PTSD_Diagnostico_UA                              <chr> "No", "No", "No", "No…
$ Violencias_infancias                             <dbl> 1, 1, 2, 0, 2, 3, 0, …
$ f32YE_Depresion_Simple_UA                        <chr> "No", "No", "Sí", "No…
$ EEV_EC_1_Fallecimiento_familiar                  <chr> "No", "No", "No", "No…
$ EEV_EC_2_Atrapado_y_rescatado                    <chr> "No", "Sí", "No", "No…
$ EEV_EC_3_Lesiones_fisicas_Graves_Hospitalizacion <chr> "No", "No", "No", "No…
$ EEV_EC_4_Daño_grave_o_Perdida_Vivienda           <chr> "No", "No", "No", "No…
$ EEV_EC_Final                                     <chr> "No", "Sí", "No", "No…
$ EEV_TE_1_Muerte_mascota                          <dbl> 0, 0, 0, 0, 0, 0, 0, …
$ EEV_TE_2_Muerte_familiar                         <dbl> 0, 0, 0, 0, 0, 0, 0, …
$ EEV_TE_3_Herido_familiar                         <dbl> 0, 1, 0, 0, 0, 0, 0, …
$ EEV_TE_4_Atrapado_y_rescatado                    <dbl> 0, 1, 0, 0, 0, 0, 0, …
$ EEV_TE_5_Lesiones_fisicas_Graves_Hospitalizacion <dbl> 0, 0, 0, 0, 0, 0, 0, …
$ EEV_TE_6_Sentir_Riesgo_vital                     <dbl> 0, 1, 0, 1, 1, 0, 0, …
$ EEV_TE_7_Tsunami_llego_cerca                     <dbl> 0, 0, 0, 0, 0, 0, 0, …
$ EEV_TE_8_Daño_grave_o_Perdida_Vivienda           <dbl> 0, 0, 0, 0, 0, 1, 0, …
$ EEV_TE_9_Victima_robos                           <dbl> 0, 0, 0, 0, 0, 0, 0, …
$ EEV_TE_10_Quedar_sin_trabajo                     <dbl> 0, 0, 0, 0, 0, 0, 0, …
$ EEV_TE_11_Presencio_personas_heridas             <dbl> 0, 1, 0, 0, 0, 0, 0, …
$ EEV_TE_12_Presencio_personas_fallecidas          <dbl> 0, 0, 0, 0, 0, 0, 0, …
$ EEV_TE_13_Participo_en_rescate_personas          <dbl> 0, 0, 0, 0, 0, 0, 0, …
$ EEV_TE_14_Vio_construcciones_destruyendose       <dbl> 0, 0, 1, 0, 0, 0, 1, …
$ EEV_TE_Suma_TOTAL                                <dbl> 0, 4, 1, 1, 1, 1, 1, …

In [5]:
#Transformar a categóricas
datos<- datos %>%
  mutate(
  a1_Sexo = as.factor(a1_Sexo),
  a8_Años_Estudio_Categoria = factor(a8_Años_Estudio_Categoria, levels= c("Basica", "Media", "Superior", "Analfabeto")),
  PTSD_Diagnostico_UA = as.factor(PTSD_Diagnostico_UA),
  EEV_EC_1_Fallecimiento_familiar = as.factor(EEV_EC_1_Fallecimiento_familiar),
  EEV_EC_2_Atrapado_y_rescatado = as.factor(EEV_EC_2_Atrapado_y_rescatado),
  EEV_EC_3_Lesiones_fisicas_Graves_Hospitalizacion = as.factor(EEV_EC_3_Lesiones_fisicas_Graves_Hospitalizacion),
  EEV_EC_4_Daño_grave_o_Perdida_Vivienda = as.factor(EEV_EC_4_Daño_grave_o_Perdida_Vivienda),
  EEV_EC_Final = as.factor(EEV_EC_Final)
  )

In [6]:
#Eliminar duplicados
sum(duplicated(datos))

[1] 0

In [7]:
head(datos)

  inum a1_Sexo   a2_Edad a8_Años_Estudio_Categoria PTSD_Diagnostico_UA
1  2   Femenino  60      Basica                    No
2  4   Femenino  64      Media                     No
3 11   Femenino  45      Media                     No
4 21   Masculino 67      Basica                    No
5 32   Femenino  73      Media                     No
6 35   Femenino  83      Basica                    No
  Violencias_infancias f32YE_Depresion_Simple_UA
1 1                    No
2 1                    No
3 2                    Sí
4 0                    No
5 2                    No
6 3                    No
  EEV_EC_1_Fallecimiento_familiar EEV_EC_2_Atrapado_y_rescatado
1 No                              No
2 No                              Sí
3 No                              No
4 No                              No
5 No                              No
6 No                              No
  EEV_EC_3_Lesiones_fisicas_Graves_Hospitalizacion ⋯
1 No                                               ⋯
2 No                                               ⋯
3 No                                               ⋯
4 No                                               ⋯
5 No                                               ⋯
6 No                                               ⋯
  EEV_TE_6_Sentir_Riesgo_vital EEV_TE_7_Tsunami_llego_cerca
1 0                            0
2 1                            0
3 0                            0
4 1                            0
5 1                            0
6 0                            0
  EEV_TE_8_Daño_grave_o_Perdida_Vivienda EEV_TE_9_Victima_robos
1 0                                      0
2 0                                      0
3 0                                      0
4 0                                      0
5 0                                      0
6 1                                      0
  EEV_TE_10_Quedar_sin_trabajo EEV_TE_11_Presencio_personas_heridas
1 0                            0
2 0                            1
3 0                            0
4 0                            0
5 0                            0
6 0                            0
  EEV_TE_12_Presencio_personas_fallecidas
1 0
2 0
3 0
4 0
5 0
6 0
  EEV_TE_13_Participo_en_rescate_personas
1 0
2 0
3 0
4 0
5 0
6 0
  EEV_TE_14_Vio_construcciones_destruyendose EEV_TE_Suma_TOTAL
1 0                                          0
2 0                                          4
3 1                                          1
4 0                                          1
5 0                                          1
6 0                                          1

Primer Análisis

In [8]:
modelo_parte1 <- glm(PTSD_Diagnostico_UA ~ Violencias_infancias + EEV_EC_Final + EEV_TE_Suma_TOTAL,
                     data = datos,
                     family = binomial(link = "logit"))
summary(modelo_parte1)

Call:
glm(formula = PTSD_Diagnostico_UA ~ Violencias_infancias + EEV_EC_Final +
    EEV_TE_Suma_TOTAL, family = binomial(link = "logit"), data = datos)

Coefficients:
                     Estimate Std. Error z value Pr(>|z|)
(Intercept)          -2.84011    0.18937 -14.998  < 2e-16 ***
Violencias_infancias  0.05947    0.10748   0.553   0.5801
EEV_EC_FinalSí       -0.60294    0.35080  -1.719   0.0857 .
EEV_TE_Suma_TOTAL     0.49575    0.07831   6.331 2.44e-10 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 635.12  on 912  degrees of freedom
Residual deviance: 590.71  on 909  degrees of freedom
AIC: 598.71

Number of Fisher Scoring iterations: 5

In [28]:
tidy(modelo_parte1, exponentiate = TRUE, conf.int = TRUE )%>%
  mutate_if(is.numeric, round, 5)

  term                 estimate std.error statistic p.value conf.low conf.high
1 (Intercept)          0.05842  0.18937   -14.99764 0.00000 0.03976  0.08362
2 Violencias_infancias 1.06127  0.10748     0.55327 0.58008 0.85598  1.30591
3 EEV_EC_FinalSí       0.54720  0.35080    -1.71873 0.08566 0.26672  1.06058
4 EEV_TE_Suma_TOTAL    1.64173  0.07831     6.33059 0.00000 1.41038  1.91894

Segundo Análisis (+ depresión + edad) estratificado por sexo

In [17]:
# Modelo solo para Mujeres
modelo_mujeres <- glm(PTSD_Diagnostico_UA ~ Violencias_infancias + EEV_EC_Final +
                      EEV_TE_Suma_TOTAL + f32YE_Depresion_Simple_UA + a2_Edad,
                      data = subset(datos, a1_Sexo == "Femenino"),
                      family = binomial(link = "logit"))
summary(modelo_mujeres)


# Modelo solo para Hombres
modelo_hombres <- glm(PTSD_Diagnostico_UA ~ Violencias_infancias + EEV_EC_Final +
                      EEV_TE_Suma_TOTAL + f32YE_Depresion_Simple_UA + a2_Edad,
                      data = subset(datos, a1_Sexo == "Masculino"),
                      family = binomial(link = "logit"))
summary(modelo_hombres)

Call:
glm(formula = PTSD_Diagnostico_UA ~ Violencias_infancias + EEV_EC_Final +
    EEV_TE_Suma_TOTAL + f32YE_Depresion_Simple_UA + a2_Edad,
    family = binomial(link = "logit"), data = subset(datos, a1_Sexo ==
        "Femenino"))

Coefficients:
                             Estimate Std. Error z value Pr(>|z|)
(Intercept)                 -2.885350   0.498735  -5.785 7.24e-09 ***
Violencias_infancias         0.010811   0.115782   0.093   0.9256
EEV_EC_FinalSí              -0.468167   0.379548  -1.233   0.2174
EEV_TE_Suma_TOTAL            0.467702   0.093937   4.979 6.39e-07 ***
f32YE_Depresion_Simple_UASí  0.677009   0.360742   1.877   0.0606 .
a2_Edad                      0.002127   0.007827   0.272   0.7858
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 519.72  on 723  degrees of freedom
Residual deviance: 486.13  on 718  degrees of freedom
AIC: 498.13

Number of Fisher Scoring iterations: 5

Call:
glm(formula = PTSD_Diagnostico_UA ~ Violencias_infancias + EEV_EC_Final +
    EEV_TE_Suma_TOTAL + f32YE_Depresion_Simple_UA + a2_Edad,
    family = binomial(link = "logit"), data = subset(datos, a1_Sexo ==
        "Masculino"))

Coefficients:
                             Estimate Std. Error z value Pr(>|z|)
(Intercept)                 -3.702816   1.167288  -3.172 0.001513 **
Violencias_infancias         0.388709   0.304956   1.275 0.202437
EEV_EC_FinalSí              -1.651852   1.118272  -1.477 0.139636
EEV_TE_Suma_TOTAL            0.614787   0.165026   3.725 0.000195 ***
f32YE_Depresion_Simple_UASí  0.973016   1.287735   0.756 0.449887
a2_Edad                      0.002202   0.018043   0.122 0.902875
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 114.313  on 188  degrees of freedom
Residual deviance:  96.627  on 183  degrees of freedom
AIC: 108.63

Number of Fisher Scoring iterations: 5

In [27]:

tidy(modelo_mujeres, exponentiate = TRUE, conf.int = TRUE) %>%
  mutate_if(is.numeric, round, 5)
tidy(modelo_hombres, exponentiate = TRUE, conf.int = TRUE)%>%
  mutate_if(is.numeric, round, 5)

  term                        estimate std.error statistic p.value conf.low
1 (Intercept)                 0.05584  0.49873   -5.78534  0.00000 0.02033
2 Violencias_infancias        1.01087  0.11578    0.09337  0.92561 0.80137
3 EEV_EC_FinalSí              0.62615  0.37955   -1.23349  0.21739 0.28811
4 EEV_TE_Suma_TOTAL           1.59632  0.09394    4.97890  0.00000 1.32928
5 f32YE_Depresion_Simple_UASí 1.96798  0.36074    1.87671  0.06056 0.93391
6 a2_Edad                     1.00213  0.00783    0.27172  0.78584 0.98686
  conf.high
1 0.14417
2 1.26347
3 1.28373
4 1.92383
5 3.88188
6 1.01768

  term                        estimate std.error statistic p.value conf.low
1 (Intercept)                 0.02465  1.16729   -3.17215  0.00151 0.00188
2 Violencias_infancias        1.47508  0.30496    1.27464  0.20244 0.79448
3 EEV_EC_FinalSí              0.19169  1.11827   -1.47715  0.13964 0.01448
4 EEV_TE_Suma_TOTAL           1.84926  0.16503    3.72539  0.00020 1.35881
5 f32YE_Depresion_Simple_UASí 2.64591  1.28774    0.75560  0.44989 0.11066
6 a2_Edad                     1.00220  0.01804    0.12203  0.90288 0.96806
  conf.high
1  0.19325
2  2.67134
3  1.27102
4  2.61529
5 25.66980
6  1.04018

In [16]:
# Modelo solo para Mujeres (agregado escolaridad)
modelo_mujeres_esc <- glm(PTSD_Diagnostico_UA ~ Violencias_infancias + EEV_EC_Final +
                      EEV_TE_Suma_TOTAL + f32YE_Depresion_Simple_UA + a2_Edad +  a8_Años_Estudio_Categoria ,
                      data = subset(datos, a1_Sexo == "Femenino"),
                      family = binomial(link = "logit"))
summary(modelo_mujeres_esc)


# Modelo solo para Hombres (agregado escolaridad)
modelo_hombres_esc <- glm(PTSD_Diagnostico_UA ~ Violencias_infancias + EEV_EC_Final +
                      EEV_TE_Suma_TOTAL + f32YE_Depresion_Simple_UA + a2_Edad +  a8_Años_Estudio_Categoria ,
                      data = subset(datos, a1_Sexo == "Masculino"),
                      family = binomial(link = "logit"))
summary(modelo_hombres_esc)

Call:
glm(formula = PTSD_Diagnostico_UA ~ Violencias_infancias + EEV_EC_Final +
    EEV_TE_Suma_TOTAL + f32YE_Depresion_Simple_UA + a2_Edad +
    a8_Años_Estudio_Categoria, family = binomial(link = "logit"),
    data = subset(datos, a1_Sexo == "Femenino"))

Coefficients:
                                      Estimate Std. Error z value Pr(>|z|)
(Intercept)                         -2.6324681  0.6593409  -3.993 6.54e-05 ***
Violencias_infancias                -0.0002904  0.1177226  -0.002   0.9980
EEV_EC_FinalSí                      -0.4771376  0.3840368  -1.242   0.2141
EEV_TE_Suma_TOTAL                    0.4716268  0.0945374   4.989 6.08e-07 ***
f32YE_Depresion_Simple_UASí          0.7147676  0.3659861   1.953   0.0508 .
a2_Edad                             -0.0021849  0.0088513  -0.247   0.8050
a8_Años_Estudio_CategoriaMedia      -0.0405687  0.3185596  -0.127   0.8987
a8_Años_Estudio_CategoriaSuperior   -0.5181581  0.4762566  -1.088   0.2766
a8_Años_Estudio_CategoriaAnalfabeto  0.5319681  0.3988972   1.334   0.1823
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 519.72  on 723  degrees of freedom
Residual deviance: 481.50  on 715  degrees of freedom
AIC: 499.5

Number of Fisher Scoring iterations: 5

Call:
glm(formula = PTSD_Diagnostico_UA ~ Violencias_infancias + EEV_EC_Final +
    EEV_TE_Suma_TOTAL + f32YE_Depresion_Simple_UA + a2_Edad +
    a8_Años_Estudio_Categoria, family = binomial(link = "logit"),
    data = subset(datos, a1_Sexo == "Masculino"))

Coefficients:
                                      Estimate Std. Error z value Pr(>|z|)
(Intercept)                         -2.362e+00  1.535e+00  -1.539 0.123861
Violencias_infancias                 3.486e-01  3.092e-01   1.127 0.259584
EEV_EC_FinalSí                      -1.461e+00  1.131e+00  -1.292 0.196509
EEV_TE_Suma_TOTAL                    6.248e-01  1.745e-01   3.581 0.000343 ***
f32YE_Depresion_Simple_UASí          1.277e+00  1.296e+00   0.985 0.324684
a2_Edad                             -9.155e-03  2.140e-02  -0.428 0.668758
a8_Años_Estudio_CategoriaMedia      -1.116e+00  7.135e-01  -1.564 0.117783
a8_Años_Estudio_CategoriaSuperior   -8.389e-01  1.028e+00  -0.816 0.414511
a8_Años_Estudio_CategoriaAnalfabeto -1.647e+01  1.706e+03  -0.010 0.992296
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 114.313  on 188  degrees of freedom
Residual deviance:  92.099  on 180  degrees of freedom
AIC: 110.1

Number of Fisher Scoring iterations: 17